POST http://localhost:8088/create-developer
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillLevel": "BACK_END",
  "experienceYears": 2,
  "memberId": "Mini",
  "name": "mouse",
  "age": 20
}